/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_seu_hwq_spider_util_Keyword */

#ifndef _Included_edu_seu_hwq_spider_util_Keyword
#define _Included_edu_seu_hwq_spider_util_Keyword
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_seu_hwq_spider_util_Keyword
 * Method:    getKeywordsbyJieba
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_seu_hwq_spider_util_Keyword_getKeywordsbyJieba
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
